### ISSUE TITLE
Not able to add stackoverflow icon in social links

### ISSUE THREAD

**Issue by deleSerna** [samarsault/plainwhite-jekyll#63]
I tried to add stackoverflow profile  as follows 
 ```
        {%- if site.plainwhite.social_links.stackoverflow -%}
        <a href="https://stackoverflow.com/users/{{ site.plainwhite.social_links.stackoverflow }}" target="_blank">
          <li>
            <i class="icon-stackoverflow"></i>
          </li>
        </a>
        {%- endif -%}
```

By following _https://github.com/jekyll/minima/pull/443/files_
 
But it did not work, stackoverflow icon was not showing. This is my first try with jekyll, may be I am missing something very basic. 
Could you let me know the issue. 
Thanks in advance

**Comment by DotIN13** [comment]
You'll also have to manually generate your own fontello font files with SO icon built in, which are located in `assets/font`. You could visit [fontello](http://fontello.com/), drag in the `assets/font/fontello-config.json`, and then add the stackoverflow icon. After downloading your own font files, extract font files to replace files in `assets/font` and css files to replace `_sass/ext/_fonts.scss`. Then you should be good to go.

**Comment by deleSerna** [comment]
Thanks it worked. I will reiterate the steps as I was bit confused
1. Click the import button and upload the assets/font/fontello-config.json
<img width="825" alt="Screen Shot 2020-06-25 at 7 37 21 PM" src="https://user-images.githubusercontent.com/5850988/85771798-8cf42800-b71c-11ea-9a8f-7ae52d8403ac.png">
2. search for stackoverflow icon and then select it. If you properly selected it then in the customNames/CustomCode tab all the icon including the stakcoverflow must 
<img width="1102" alt="Screen Shot 2020-06-25 at 7 48 05 PM" src="https://user-images.githubusercontent.com/5850988/85772206-e65c5700-b71c-11ea-8fc3-ae6a3aad7b0e.png">
be visible
3. Download  the files and replace the files in assets/font
4.  Replace  content of _sass/ext/_fonts.scss with css/fontello.css from the download folder
5. Modify  _layouts/default.html by adding following
```{%- if site.plainwhite.social_links.stackoverflow -%}
       <a href="https://stackoverflow.com/users/{{ site.plainwhite.social_links.stackoverflow }}" target="_blank">
         <li>
           <i class="icon-stackoverflow"></i>
         </li>
       </a>
       {%- endif -%}```
6. Commit and build. It should work fine
