### ISSUE TITLE
Not able to load images from  assets directory in the post

### ISSUE THREAD

**Issue by deleSerna** [samarsault/plainwhite-jekyll#67]
I tried to refer an image from my post as ![Deployment diagram](../assets/images/2019-03-23-springboot/springbootonkubernetes.png). I can see the image in the preview but in the final post it's showing as broken 
https://deleserna.github.io/java/springboot/kubernetes/elasticsearch/2020/06/12/welcome-to-jekyll.html

**Comment by DotIN13** [comment]
As the assets folder was placed under site root while post files were placed several layers deep depending on your permenant URL settings, the correct image URL should be `/assets/images/2019-03-23-springboot/springbootonkubernetes.png` instead of `../assets/images...`.

**Comment by deleSerna** [comment]
Thanks it worked
