### ISSUE TITLE
How to add readmore feature on posts

### ISSUE THREAD

**Issue by deleSerna** [samarsault/plainwhite-jekyll#68]
Hi, 
I am planning to add read more link on the home page for every posts. 
I tried method mentioned in http://dev.im-bot.com/read-more-jekyll/ ( added in index.md and in my post)
and  here https://muffinman.io/jekyll-read-more-link/. But none of them did not work.
Could you please let me know the proper way to do that

**Comment by DotIN13** [comment]
You should be adding lines to `_layout/home.html` instead of index.md.

You will need to modify `_layout/home.html: 53`. For more details, plz refer to my answer in #56 .

**Comment by deleSerna** [comment]
Thanks it worked
