### ISSUE TITLE
[Feature Request] GitLab Link

### ISSUE THREAD

**Issue by AlexVerrico** [samarsault/plainwhite-jekyll#70]
Hi.
Would it be possible to add an option for a link to a GitLab profile like all of the other social links in this template?
I would add it myself, but I'm not sure how to edit the font files, so if someone could point me in the right direction the I can have a crack at it 😉.
Cheers,
Alex.

**Comment by samarsault** [comment]
Check this https://github.com/samarsault/plainwhite-jekyll/issues/63#issuecomment-649730006

**Comment by AlexVerrico** [comment]
Thanks for that, I'll have a go at following that guide tomorrow.
Cheers,
Alex.

**Comment by AlexVerrico** [comment]
Done in PR #74
