### ISSUE TITLE
Update Gem.

### ISSUE THREAD

**Issue by AlexVerrico** [samarsault/plainwhite-jekyll#75]
Hi @samarsault 
The gem for this plugin says that the most recent release was 22nd of May (See [rubygems.org/gems/plainwhite/versions/0.11](https://rubygems.org/gems/plainwhite/versions/0.11)
Any chance you can release a new version with recent channges?
Cheers,
Alex.

**Comment by samarsault** [comment]
I'm planing to release the latest gem once #65 is closed.

**Comment by AlexVerrico** [comment]
Looks like #65 hasn't had any changes in a month? Maybe worth pinging whoever opened the PR?

**Comment by AlexVerrico** [comment]
Hi @samarsault 
Considering it has now been over a week since you asked @minhrongcon2000 about #65, I would like to request that you update the gem with the current changes, and then update it again if/when @minhrongcon2000 finishes that PR.
Cheers,
Alex.

**Comment by samarsault** [comment]
Closed in https://github.com/samarsault/plainwhite-jekyll/commit/35db1131767c3733cd4fcbc581890198a0c3e851
