### ISSUE TITLE
Place navigation at bottom on mobile

### ISSUE THREAD

**Issue by oyvn** [samarsault/plainwhite-jekyll#78]
I noticed that on mobile, the top is completely covered by the name, portfolio_image, and navigation. This means that all my pages look the same when loading, and you have to scroll to see a difference (since the top is the same on all pages).

If the navigation could be moved to the bottom on mobile, it might help bring the title of the page into view when the page loads. It can stay in the same place in the sidebar on desktop.

**Comment by samarsault** [comment]
Yes, I agree. I really like how @Krinkle's handles this (See https://github.com/samarsault/plainwhite-jekyll/issues/76).
It might take me a while to do this, any PR is welcome.

**Comment by oyvn** [comment]
That looks very nice! Another option is to move the copyright to the bottom.
