### ISSUE TITLE
Sample Post layout and header

### ISSUE THREAD

**Issue by sonasapps** [samarsault/plainwhite-jekyll#98]
Thanks for this theme, I really like it!
Can I see a sample of the post header, as well as it's layout within the site? (assuming it's just under a _posts directory on root?)

I installed via just adding the remote theme to my _config so I don't see any sample post data. Thanks!

**Comment by samarsault** [comment]
You can check out https://samarsault.com/

**Comment by sonasapps** [comment]
Thanks, more looking for what header content is supported by default within a post

**Comment by samarsault** [comment]
I'm not sure what you mean by header content. There is the post title, date & tags for now.

**Comment by sonasapps** [comment]
That answers it, thanks!
